[versions]
agp = "8.2.2"
kotlin = "1.9.22"
core-ktx = "1.12.0"
appcompat = "1.6.1"
material = "1.11.0"
activity = "1.8.2"
constraintlayout = "2.1.4"
junit = "4.13.2"
androidx-junit = "1.1.5"
espresso-core = "3.5.1"
nanohttpd = "2.3.1"
kotlinx-serialization = "1.6.0"
gson = "2.10.1"
support-annotations = "28.0.0"
core = "1.0.0"
printerlibrary = "1.0.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-junit" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
nanohttpd = { group = "org.nanohttpd", name = "nanohttpd", version.ref = "nanohttpd" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
support-annotations = { group = "com.android.support", name = "support-annotations", version.ref = "support-annotations" }
core = { group = "com.github.core", name = "core", version.ref = "core" }
printerlibrary = { group = "com.github.printer", name = "printerlibrary", version.ref = "printerlibrary" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }


