# Service without selector to define external endpoint
apiVersion: v1
kind: Service
metadata:
  name: image-compression
  namespace: default
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: img-compress

---
# Endpoints to specify the external IP
apiVersion: v1
kind: Endpoints
metadata:
  name: image-compression
  namespace: default
subsets:
  - addresses:
      - ip: 140.245.222.124 # Updated to your public IP
    ports:
      - port: 3000
        name: img-compress

---
# Ingress for external service
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: image-compression-ingress
  namespace: default
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: 'true'
spec:
  tls:
    - hosts:
        - qa-k8s.tisostudio.com
      secretName: tijarah-ingress
  rules:
    - host: qa-k8s.tisostudio.com
      http:
        paths:
          - path: /image-compression
            pathType: Prefix
            backend:
              service:
                name: image-compression
                port:
                  name: img-compress
