name: GitlabSync

on:
  push:
    branches:
      - development
  delete:
    branches:
      - development

jobs:
  sync:
    runs-on: ubuntu-latest
    name: Git Repo Sync
    steps:
      - uses: actions/checkout@v2
      - uses: adambirds/sync-github-to-gitlab-action@v1.1.0
        with:
          destination_repository: git@gitlab.com:tijarah/web-ar-menu.git
          destination_branch_name: development
          destination_ssh_key: ${{ secrets.GITLAB_SSH_KEY }}
